package entity.orderonline.api.fpx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:18:45.751+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "entity.orderonline.api.fpx", name = "IOrderOnlineService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOrderOnlineService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "preAlertOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.PreAlertOrderService")
    @WebMethod
    @ResponseWrapper(localName = "preAlertOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.PreAlertOrderServiceResponse")
    public java.util.List<entity.orderonline.api.fpx.PreAlertOrderResponse> preAlertOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.RemoveOrderService")
    @WebMethod
    @ResponseWrapper(localName = "removeOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.RemoveOrderServiceResponse")
    public java.util.List<entity.orderonline.api.fpx.RemoveOrderResponse> removeOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.FindOrderService")
    @WebMethod
    @ResponseWrapper(localName = "findOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.FindOrderServiceResponse")
    public entity.orderonline.api.fpx.FindOrderResponse findOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        entity.orderonline.api.fpx.FindOrderRequest arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.CreateOrderService")
    @WebMethod
    @ResponseWrapper(localName = "createOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.CreateOrderServiceResponse")
    public java.util.List<entity.orderonline.api.fpx.CreateOrderResponse> createOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<entity.orderonline.api.fpx.CreateOrderRequest> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createAndPreAlertOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.CreateAndPreAlertOrderService")
    @WebMethod
    @ResponseWrapper(localName = "createAndPreAlertOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.CreateAndPreAlertOrderServiceResponse")
    public java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderResponse> createAndPreAlertOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderRequest> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "modifyOrderService", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.ModifyOrderService")
    @WebMethod
    @ResponseWrapper(localName = "modifyOrderServiceResponse", targetNamespace = "entity.orderonline.api.fpx", className = "entity.orderonline.api.fpx.ModifyOrderServiceResponse")
    public java.util.List<entity.orderonline.api.fpx.ModifyOrderResponse> modifyOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<entity.orderonline.api.fpx.ModifyOrderRequest> arg1
    );
}
