package entity.orderonline.api.fpx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:18:45.756+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "OrderOnlineServiceImplService", 
                  wsdlLocation = "http://api.ruston.cc/OrderOnline/ws/OrderOnlineService.dll?wsdl",
                  targetNamespace = "entity.orderonline.api.fpx") 
public class OrderOnlineServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("entity.orderonline.api.fpx", "OrderOnlineServiceImplService");
    public final static QName OrderOnlineServiceImplPort = new QName("entity.orderonline.api.fpx", "OrderOnlineServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://api.ruston.cc/OrderOnline/ws/OrderOnlineService.dll?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderOnlineServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://api.ruston.cc/OrderOnline/ws/OrderOnlineService.dll?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderOnlineServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderOnlineServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderOnlineServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IOrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServiceImplPort")
    public IOrderOnlineService getOrderOnlineServiceImplPort() {
        return super.getPort(OrderOnlineServiceImplPort, IOrderOnlineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServiceImplPort")
    public IOrderOnlineService getOrderOnlineServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderOnlineServiceImplPort, IOrderOnlineService.class, features);
    }

}
