
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package entity.orderonline.api.tool;

import java.util.logging.Logger;
/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:14:34.258+08:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderOnlineToolServiceImplService",
                      portName = "OrderOnlineToolServiceImplPort",
                      targetNamespace = "entity.orderonlinetool.api.fpx",
                      wsdlLocation = "http://api.ruston.cc/OrderOnlineTool/ws/OrderOnlineToolService.dll?wsdl",
                      endpointInterface = "entity.orderonline.api.tool.IOrderOnlineToolService")
                      
public class IOrderOnlineToolServiceImpl implements IOrderOnlineToolService {

    private static final Logger LOG = Logger.getLogger(IOrderOnlineToolServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#chargeCalculateService(java.lang.String  arg0 ,)entity.orderonline.api.tool.ChargeCalculateRequest  arg1 )*
     */
    public entity.orderonline.api.tool.ChargeCalculateResponse chargeCalculateService(java.lang.String arg0,entity.orderonline.api.tool.ChargeCalculateRequest arg1) { 
        LOG.info("Executing operation chargeCalculateService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            entity.orderonline.api.tool.ChargeCalculateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#printLableService(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public entity.orderonline.api.tool.PrintLableResponse printLableService(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation printLableService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            entity.orderonline.api.tool.PrintLableResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#cargoHoldService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.tool.CargoHoldResponse> cargoHoldService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation cargoHoldService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.tool.CargoHoldResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#cargoTrackingService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.tool.CargoTrackingResponse> cargoTrackingService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation cargoTrackingService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.tool.CargoTrackingResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#findLabelDataService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.tool.FindLabelDataResponse> findLabelDataService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation findLabelDataService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.tool.FindLabelDataResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.tool.IOrderOnlineToolService#findTrackingNumberService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.tool.FindTrackingNumberResponse> findTrackingNumberService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation findTrackingNumberService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.tool.FindTrackingNumberResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
