
package entity.orderonline.api.tool;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:14:34.220+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class IOrderOnlineToolService_OrderOnlineToolServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("entity.orderonlinetool.api.fpx", "OrderOnlineToolServiceImplService");

    private IOrderOnlineToolService_OrderOnlineToolServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderOnlineToolServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderOnlineToolServiceImplService ss = new OrderOnlineToolServiceImplService(wsdlURL, SERVICE_NAME);
        IOrderOnlineToolService port = ss.getOrderOnlineToolServiceImplPort();  
        
       /* {
        //System.out.println("Invoking chargeCalculateService...");
        java.lang.String _chargeCalculateService_arg0 = "";
        entity.orderonline.api.tool.ChargeCalculateRequest _chargeCalculateService_arg1 = null;
        entity.orderonline.api.tool.ChargeCalculateResponse _chargeCalculateService__return = port.chargeCalculateService(_chargeCalculateService_arg0, _chargeCalculateService_arg1);
        //System.out.println("chargeCalculateService.result=" + _chargeCalculateService__return);


        }*/
        /*{
        //System.out.println("Invoking printLableService...");
        java.lang.String _printLableService_arg0 = "";
        java.lang.String _printLableService_arg1 = "";
        entity.orderonline.api.tool.PrintLableResponse _printLableService__return = port.printLableService(_printLableService_arg0, _printLableService_arg1);
        //System.out.println("printLableService.result=" + _printLableService__return);


        }*/
       /* {
        //System.out.println("Invoking cargoHoldService...");
        java.lang.String _cargoHoldService_arg0 = "";
        java.util.List<java.lang.String> _cargoHoldService_arg1 = null;
        java.util.List<entity.orderonline.api.tool.CargoHoldResponse> _cargoHoldService__return = port.cargoHoldService(_cargoHoldService_arg0, _cargoHoldService_arg1);
        //System.out.println("cargoHoldService.result=" + _cargoHoldService__return);


        }*/
        {
        //System.out.println("Invoking cargoTrackingService...");
        java.lang.String _cargoTrackingService_arg0 = "8BC17B74BD800FEB35F5E7A2DB282ED8";
        java.util.List<java.lang.String> _cargoTrackingService_arg1 = new ArrayList<String>();
        _cargoTrackingService_arg1.add("1002520150422151603");
        java.util.List<entity.orderonline.api.tool.CargoTrackingResponse> _cargoTrackingService__return = port.cargoTrackingService(_cargoTrackingService_arg0, _cargoTrackingService_arg1);
        //System.out.println("cargoTrackingService.result=" + _cargoTrackingService__return);


        }
       /* {
        //System.out.println("Invoking findLabelDataService...");
        java.lang.String _findLabelDataService_arg0 = "";
        java.util.List<java.lang.String> _findLabelDataService_arg1 = null;
        java.util.List<entity.orderonline.api.tool.FindLabelDataResponse> _findLabelDataService__return = port.findLabelDataService(_findLabelDataService_arg0, _findLabelDataService_arg1);
        //System.out.println("findLabelDataService.result=" + _findLabelDataService__return);


        }*/
        /*{
        //System.out.println("Invoking findTrackingNumberService...");
        java.lang.String _findTrackingNumberService_arg0 = "";
        java.util.List<java.lang.String> _findTrackingNumberService_arg1 = null;
        java.util.List<entity.orderonline.api.tool.FindTrackingNumberResponse> _findTrackingNumberService__return = port.findTrackingNumberService(_findTrackingNumberService_arg0, _findTrackingNumberService_arg1);
        //System.out.println("findTrackingNumberService.result=" + _findTrackingNumberService__return);


        }*/

        System.exit(0);
    }

}
