
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.orderonline.api.tool;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-10-26T15:50:52.866+08:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderOnlineToolServiceImplService",
                      portName = "OrderOnlineToolServiceImplPort",
                      targetNamespace = "entity.orderonlinetool.api.fpx",
                      wsdlLocation = "http://api.ets-express.com/OrderOnlineTool/ws/OrderOnlineToolService.dll?wsdl",
                      endpointInterface = "com.orderonline.api.extTool.IOrderOnlineToolService")
                      
public class IOrderOnlineToolServiceImpl implements IOrderOnlineToolService {

    private static final Logger LOG = Logger.getLogger(IOrderOnlineToolServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#chargeCalculateService(java.lang.String  arg0 ,)com.orderonline.api.extTool.ChargeCalculateRequest  arg1 )*
     */
    public com.orderonline.api.tool.ChargeCalculateResponse chargeCalculateService(java.lang.String arg0,com.orderonline.api.tool.ChargeCalculateRequest arg1) { 
        LOG.info("Executing operation chargeCalculateService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            com.orderonline.api.tool.ChargeCalculateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#printLableService(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public com.orderonline.api.tool.PrintLableResponse printLableService(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation printLableService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            com.orderonline.api.tool.PrintLableResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#cargoHoldService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<com.orderonline.api.tool.CargoHoldResponse> cargoHoldService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation cargoHoldService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<com.orderonline.api.tool.CargoHoldResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#cargoTrackingService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<com.orderonline.api.tool.CargoTrackingResponse> cargoTrackingService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation cargoTrackingService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<com.orderonline.api.tool.CargoTrackingResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#findLabelDataService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<com.orderonline.api.tool.FindLabelDataResponse> findLabelDataService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation findLabelDataService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<com.orderonline.api.tool.FindLabelDataResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.orderonline.api.extTool.IOrderOnlineToolService#findTrackingNumberService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<com.orderonline.api.tool.FindTrackingNumberResponse> findTrackingNumberService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation findTrackingNumberService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<com.orderonline.api.tool.FindTrackingNumberResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
