package entity.orderonline.api.tool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:14:34.274+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "OrderOnlineToolServiceImplService", 
                  wsdlLocation = "http://api.ruston.cc/OrderOnlineTool/ws/OrderOnlineToolService.dll?wsdl",
                  targetNamespace = "entity.orderonlinetool.api.fpx") 
public class OrderOnlineToolServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("entity.orderonlinetool.api.fpx", "OrderOnlineToolServiceImplService");
    public final static QName OrderOnlineToolServiceImplPort = new QName("entity.orderonlinetool.api.fpx", "OrderOnlineToolServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://api.ruston.cc/OrderOnlineTool/ws/OrderOnlineToolService.dll?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderOnlineToolServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://api.ruston.cc/OrderOnlineTool/ws/OrderOnlineToolService.dll?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderOnlineToolServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderOnlineToolServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderOnlineToolServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineToolServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineToolServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineToolServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IOrderOnlineToolService
     */
    @WebEndpoint(name = "OrderOnlineToolServiceImplPort")
    public IOrderOnlineToolService getOrderOnlineToolServiceImplPort() {
        return super.getPort(OrderOnlineToolServiceImplPort, IOrderOnlineToolService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrderOnlineToolService
     */
    @WebEndpoint(name = "OrderOnlineToolServiceImplPort")
    public IOrderOnlineToolService getOrderOnlineToolServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderOnlineToolServiceImplPort, IOrderOnlineToolService.class, features);
    }

}
