package com.orderonline.api.tool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-10-26T15:50:52.886+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "entity.orderonlinetool.api.fpx", name = "IOrderOnlineToolService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOrderOnlineToolService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "chargeCalculateService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.ChargeCalculateService")
    @WebMethod
    @ResponseWrapper(localName = "chargeCalculateServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.ChargeCalculateServiceResponse")
    public com.orderonline.api.tool.ChargeCalculateResponse chargeCalculateService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.orderonline.api.tool.ChargeCalculateRequest arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "printLableService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.PrintLableService")
    @WebMethod
    @ResponseWrapper(localName = "printLableServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.PrintLableServiceResponse")
    public com.orderonline.api.tool.PrintLableResponse printLableService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cargoHoldService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.CargoHoldService")
    @WebMethod
    @ResponseWrapper(localName = "cargoHoldServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.CargoHoldServiceResponse")
    public java.util.List<com.orderonline.api.tool.CargoHoldResponse> cargoHoldService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cargoTrackingService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.CargoTrackingService")
    @WebMethod
    @ResponseWrapper(localName = "cargoTrackingServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.CargoTrackingServiceResponse")
    public java.util.List<com.orderonline.api.tool.CargoTrackingResponse> cargoTrackingService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findLabelDataService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.FindLabelDataService")
    @WebMethod
    @ResponseWrapper(localName = "findLabelDataServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.FindLabelDataServiceResponse")
    public java.util.List<com.orderonline.api.tool.FindLabelDataResponse> findLabelDataService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findTrackingNumberService", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.FindTrackingNumberService")
    @WebMethod
    @ResponseWrapper(localName = "findTrackingNumberServiceResponse", targetNamespace = "entity.orderonlinetool.api.fpx", className = "com.orderonline.api.tool.FindTrackingNumberServiceResponse")
    public java.util.List<com.orderonline.api.tool.FindTrackingNumberResponse> findTrackingNumberService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );
}
