package com.enation.app.shop.core.model;

import com.enation.framework.database.PrimaryKeyField;



/**
 * Activity generated by MyEclipse - Hibernate Tools
 */

public class RouteRu  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String track_code;
     private String track_content;
     private String occur_date;
     private String occur_address;
     private String tracking_number;
     private String reference_Number;
    
	
	public String getReference_Number() {
		return reference_Number;
	}
	public void setReference_Number(String reference_Number) {
		this.reference_Number = reference_Number;
	}
	public String getTrack_code() {
		return track_code;
	}
	public void setTrack_code(String track_code) {
		this.track_code = track_code;
	}
	public String getTrack_content() {
		return track_content;
	}
	public void setTrack_content(String track_content) {
		this.track_content = track_content;
	}
	public String getOccur_date() {
		return occur_date;
	}
	public void setOccur_date(String occur_date) {
		this.occur_date = occur_date;
	}
	public String getOccur_address() {
		return occur_address;
	}
	public void setOccur_address(String occur_address) {
		this.occur_address = occur_address;
	}
	public String getTracking_number() {
		return tracking_number;
	}
	public void setTracking_number(String tracking_number) {
		this.tracking_number = tracking_number;
	}
	@PrimaryKeyField
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	

     
}