package com.enation.app.shop.core.model;

import com.enation.framework.database.PrimaryKeyField;



/**
 * Activity generated by MyEclipse - Hibernate Tools
 */

public class Route  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String mailno;
     private String remark;
     private String accept_time;
     private String accept_address;
     private String opcode;

    
	
	@PrimaryKeyField
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMailno() {
		return mailno;
	}
	public void setMailno(String mailno) {
		this.mailno = mailno;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getAccept_time() {
		return accept_time;
	}
	public void setAccept_time(String accept_time) {
		this.accept_time = accept_time;
	}
	public String getAccept_address() {
		return accept_address;
	}
	public void setAccept_address(String accept_address) {
		this.accept_address = accept_address;
	}
	public String getOpcode() {
		return opcode;
	}
	public void setOpcode(String opcode) {
		this.opcode = opcode;
	}
	

     
}