package com.enation.app.shop.core.model;

import com.enation.framework.database.PrimaryKeyField;



/**
 * Activity generated by MyEclipse - Hibernate Tools
 */

public class RouteOrder  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String mailno;
     private String orderid;
     private String origincode;
     private String destcode;
     private String filter_result;
     private String agent_mailno;
    
	
	@PrimaryKeyField
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMailno() {
		return mailno;
	}
	public void setMailno(String mailno) {
		this.mailno = mailno;
	}
	public String getOrderid() {
		return orderid;
	}
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}
	public String getOrigincode() {
		return origincode;
	}
	public void setOrigincode(String origincode) {
		this.origincode = origincode;
	}
	public String getDestcode() {
		return destcode;
	}
	public void setDestcode(String destcode) {
		this.destcode = destcode;
	}
	public String getFilter_result() {
		return filter_result;
	}
	public void setFilter_result(String filter_result) {
		this.filter_result = filter_result;
	}
	public String getAgent_mailno() {
		return agent_mailno;
	}
	public void setAgent_mailno(String agent_mailno) {
		this.agent_mailno = agent_mailno;
	}


     
}