
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package entity.orderonline.api.fpx;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-19T17:18:45.742+08:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderOnlineServiceImplService",
                      portName = "OrderOnlineServiceImplPort",
                      targetNamespace = "entity.orderonline.api.fpx",
                      wsdlLocation = "http://api.ruston.cc/OrderOnline/ws/OrderOnlineService.dll?wsdl",
                      endpointInterface = "entity.orderonline.api.fpx.IOrderOnlineService")
                      
public class IOrderOnlineServiceImpl implements IOrderOnlineService {

    private static final Logger LOG = Logger.getLogger(IOrderOnlineServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#preAlertOrderService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.fpx.PreAlertOrderResponse> preAlertOrderService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation preAlertOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.fpx.PreAlertOrderResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#removeOrderService(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.fpx.RemoveOrderResponse> removeOrderService(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation removeOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.fpx.RemoveOrderResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#findOrderService(java.lang.String  arg0 ,)entity.orderonline.api.fpx.FindOrderRequest  arg1 )*
     */
    public entity.orderonline.api.fpx.FindOrderResponse findOrderService(java.lang.String arg0,entity.orderonline.api.fpx.FindOrderRequest arg1) { 
        LOG.info("Executing operation findOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            entity.orderonline.api.fpx.FindOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#createOrderService(java.lang.String  arg0 ,)java.util.List<entity.orderonline.api.fpx.CreateOrderRequest>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.fpx.CreateOrderResponse> createOrderService(java.lang.String arg0,java.util.List<entity.orderonline.api.fpx.CreateOrderRequest> arg1) { 
        LOG.info("Executing operation createOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.fpx.CreateOrderResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#createAndPreAlertOrderService(java.lang.String  arg0 ,)java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderRequest>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderResponse> createAndPreAlertOrderService(java.lang.String arg0,java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderRequest> arg1) { 
        LOG.info("Executing operation createAndPreAlertOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.fpx.CreateAndPreAlertOrderResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see entity.orderonline.api.fpx.IOrderOnlineService#modifyOrderService(java.lang.String  arg0 ,)java.util.List<entity.orderonline.api.fpx.ModifyOrderRequest>  arg1 )*
     */
    public java.util.List<entity.orderonline.api.fpx.ModifyOrderResponse> modifyOrderService(java.lang.String arg0,java.util.List<entity.orderonline.api.fpx.ModifyOrderRequest> arg1) { 
        LOG.info("Executing operation modifyOrderService");
        //System.out.println(arg0);
        //System.out.println(arg1);
        try {
            java.util.List<entity.orderonline.api.fpx.ModifyOrderResponse> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
